
import prisma from './prismadb';


export async function addNote(title: string, content: string, email: string) {

        const findNote = await prisma.note.findFirst({
            where: {
                email, title, content
            }
        })
        console.log("foundnotes", findNote)
        if (!findNote){
            const note = await prisma.note.create({
                data: {
                    title,
                    content,
                    email,
                },
            });
            console.log("successfully created note")
            return JSON.stringify(note);
        }
        else{
            return JSON.stringify({error: "Note already exists"});
        }
        
}
export async function getNotesByEmail(email: string){
   try{const notes = await prisma.note.findMany({
        where: {
            email: email
        }
    });
    console.log("Notes retrieved from database");
    return JSON.stringify(notes);
}
    catch{
        return JSON.stringify({error: "No notes have been generated by this user"});
    }
}